spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
