apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: training
  labels:
    app: consumer-app
  name: consumer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer-app
  strategy: {}
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - image: consumer-app:0.0.1
          name: consumer-app
          env:
            - name: "KAFKA_HOST"
              value: "host.docker.internal"
            - name: "KAFKA_PORT"
              value: 9093
          resources: {}



