spring:
  application:
    name: calculator-result-consumer
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="bitnami"
    consumer:
      auto-offset-reset: earliest
      group-id: calculator-result-consumer-dev

calculator:
  topics:
    square: square-topic
    increment: increment-topic