

spring:
  cloud:
    stream:
      function:
        definition: movieConsumer
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
                      configuration:
                        security.protocol: PLAINTEXT
                        sasl.mechanism: PLAIN
                        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="bitnami";
      bindings:
        movieConsumer-in-0:
          destination: movie-topic
          group: movie-consumer-local
          consumer:
            max-attempts: 5
          configuration:
            value-deserializer: com.herbalife.lab08consumerapp.consumer.MovieCustomErrorHandlingDeserializer
            spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
            auto-offset-reset: earliest

  application:
    name: lab08-consumer-app
