spring:
  application:
    name: calculator-db-consumer
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="bitnami"
    consumer:
      auto-offset-reset: earliest
      group-id: calculator-db-consumer-dev
  datasource:
    url: jdbc:mysql://localhost:3306/training
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

calculator:
  topics:
    square: square-topic
    increment: increment-topic