services:
  palindrome-api:
    image: palindrome-api:1.0.0
    container_name: palindrome-api-1
    build:
      context: ./palindrome-api
    ports:
      - 9090:8080
  word-play-api:
    image: word-play-api:1.0.0
    container_name: word-play-api-1
    build:
      context: ./word-play-api
    ports:
      - 9091:8080
    environment:
      - PALINDROME_API_HOST=host.docker.internal
      - PALINDROME_API_PORT=9090
    depends_on:
      - palindrome-api