apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: training
  labels:
    app: palindrome-api
  name: palindrome-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palindrome-api
  strategy: {}
  template:
    metadata:
      labels:
        app: palindrome-api
    spec:
      containers:
        - image: palindrome-api:1.0.0
          name: palindrome-api
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: training
  name: palindrome-api
spec:
  selector:
    app: palindrome-api
  type: NodePort
  ports:
    - name: http
      # port: 80 refers to the port where NodePort service is running
      port: 80
      #targetPort: 8080 refers to the port that your requests get forwarded to
      targetPort: 8080
      #nodePort:30001 is what you use to access this service
      nodePort: 30001
      protocol: TCP


