spring:
  datasource:
    url: jdbc:mysql://localhost/training
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      function:
        definition: squaredNumberConsumer
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="bitnami";
            sasl.mechanism: PLAIN
            security.protocol: PLAINTEXT
          producer-properties:
            value.serializer: org.apache.kafka.common.serialization.StringSerializer
        bindings:
          squaredNumberConsumer-in-0:
            configuration:
              value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
              spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      bindings:
        number-out-0:
          destination: number-topic
          producer:
            use-native-encoding: true
        squaredNumberConsumer-in-0:
          destination: number-topic
          group: number-topic-consumer-group-local211121
          consumer:
            batch-mode: true
  application:
    name: misc-app

#spring:
#  datasource:
#    url: jdbc:mysql://localhost/training
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    stream:
#      function:
#        definition: squaredNumberConsumer
#      kafka:
#        binder:
#          brokers: localhost:9092
#          configuration:
#            security.protocol: PLAINTEXT
#            sasl.mechanism: PLAIN
#            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="bitnami";
#        bindings:
#        number-out-0:
#          destination: number-topic
#          producer:
#            use-native-encoding: true
#        squaredNumberConsumer-in-0:
#          destination: number-topic
#          group: number-topic-consumer-group-local211121
#      kafka:
#        bindings:
#          number-out-0:
#            producer:
#              configuration:
#                value.serializer: org.apache.kafka.common.serialization.StringSerializer
#          squaredNumberConsumer-in-0:
#            consumer:
#              configuration:
#                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081
